DROP FUNCTION IF EXISTS id_from_uri(INT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS add_despesas_by_file() CASCADE;
DROP FUNCTION IF EXISTS testa_valor() CASCADE;
DROP FUNCTION IF EXISTS testa_duracao() CASCADE;
