DROP TABLE IF EXISTS proposicoes CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS legislaturas CASCADE;
DROP TABLE IF EXISTS tipos_proposicao CASCADE;
DROP TABLE IF EXISTS blocos CASCADE;
DROP TABLE IF EXISTS partidos CASCADE;
