DROP SEQUENCE IF EXISTS usuarios_id_usuario_seq CASCADE;

DROP TABLE IF EXISTS deputados_proposicoes CASCADE;
DROP TABLE IF EXISTS inscricoes CASCADE;
DROP TABLE IF EXISTS mandatos CASCADE;
DROP TABLE IF EXISTS votos CASCADE;
DROP TABLE IF EXISTS blocos CASCADE;
DROP TABLE IF EXISTS legislaturas CASCADE;
DROP TABLE IF EXISTS partidos CASCADE;
DROP TABLE IF EXISTS proposicoes CASCADE;
DROP TABLE IF EXISTS tipos_proposicao CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS gabinetes CASCADE;
DROP TABLE IF EXISTS deputados CASCADE;
DROP TABLE IF EXISTS despesas CASCADE;
